name: example-stack
services:
  nextcloud:
  #   container_name: test-nextcloud
    ports:
    - 8080:80
    image: ghcr.io/mase3206/nc-scim-nextcloud-test-server:latest
    # build:
    #   context: tests/
    #   dockerfile: Dockerfile.nctest
    depends_on:
    - database-mysql
    - redis
    healthcheck:
      test: ["CMD", "bash", "/root/healthcheck.sh"]
      interval: 10s
      timeout: 1m
      retries: 30
      start_period: 30s

  database-mysql:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    command: [ '--wait_timeout=28800', ]
    ports:
      - "127.0.0.1:8212:3306"

  redis:
    image: redis:8

  nc-scim:
    ports:
    - 8000:8000
    image: ghcr.io/mase3206/nc-scim:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - nextcloud
    environment:
      SCIM_TOKEN: ""
      NEXTCLOUD_BASEURL: "nextcloud:80"
      NEXTCLOUD_HTTPS: false
      NEXTCLOUD_USERNAME: "admin"
      NEXTCLOUD_SECRET: "admin"
