name: Run PyTest against a test Nextcloud server
on:
  push:
    branches:
      - '*'

env:
  SCIM_TOKEN: ""
  NEXTCLOUD_BASEURL: "localhost:8080"
  NEXTCLOUD_HTTPS: false
  NEXTCLOUD_USERNAME: "admin"
  NEXTCLOUD_SECRET: "admin"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        curl -sSL https://bit.ly/install-xq | sudo bash

    - name: Get the code from github
      uses: actions/checkout@v2
      with:
        submodules: false

    - name: Start the Nextcloud dev server
      uses: hoverkraft-tech/compose-action@v2.3.0
      with:
        compose-file: ./tests/docker-compose.yml
        up-flags: '--force-recreate -d --wait --wait-timeout 300'
        down-flags: '-v'
        services-log-level: info
        compose-flags: '--progress plain'

    - name: Setup Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Add Poetry to PATH
      shell: bash
      run: echo "/root/.local/bin" >> $GITHUB_PATH

    - name: Install poetry
      uses: abatilo/actions-poetry@v4

    - name: Setup a local virtual environment (if no poetry.toml file)
      run: |
        poetry config virtualenvs.create true --local
        poetry config virtualenvs.in-project true --local

    - uses: actions/cache@v3
      name: Define a cache for the virtual environment based on the dependencies lock file
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: Install the project dependencies
      run: |
        poetry install
        poetry install --with=test

    - name: Configure local dev .env file
      run: |
        make env

    - name: Create users and add them to groups for testing
      run: eval $(cat .env) ./tests/prep-users-and-groups.sh

    - name: Run pytest
      run:  poetry run pytest
